---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: storm-nimbus
    run_list:
      - recipe[apt]
      - recipe[storm-cluster::nimbus]
    attributes:
      storm:
        install_method: 'remote_file'
