---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: storm-nimbus
    run_list:
      - recipe[storm-cluster::nimbus]
    attributes:
      storm:
        install_method: "remote_file"
  - name: storm-supervisor
    run_list:
      - recipe[storm-cluster::supervisor]
    attributes:
      storm:
        install_method: "remote_file"
